<a href="https://colab.research.google.com/github/ridwanmd/CEE_676_Python_Lecture/blob/main/ReferenceModules/03_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
Numpy is a library for scientific computing. It provides tools for working with multidimensional arrays (vectors, matrices). The basic data type (`class`) in Numpy is the *Numpy array*


## array creation
scaler value,
1D array,
2D array,
3D array,
MultiDimentionsal Array

## numpy attibutes
First, we will see how to create an array. Let’s take a variable a using np.array, and we want to pass a list, for example [1, 2, 3].

np.dtype → gives the data type of the array (e.g., 4 bytes → 4 bytes × 8 = 32 bits).

np.shape → gives the shape of the array. For example, [[1, 2, 3], [4, 5, 6]] has 2 rows and 3 columns.

ndim → gives the number of dimensions.

itemsize → tells how much memory each item in the array consumes. Every element takes the same amount of memory.

nbytes → gives the total memory consumed by all the elements in the array.

np. zeros, np.ones, np. empty, np.eye, np.diag, np.arrage (start, end, step) np.linespace

First you need to import the library:

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3]) # 1-D / Vector
print(a)


[1 2 3]


In [5]:
# check the type of an array
type(a)



numpy.ndarray

In [ ]:
# shape of the array
a.shape

In [ ]:
# dimension of the array
a.ndim

We start with a one-dimensional array, or vector. Now we want to create a two-dimensional array. The first row is given, and then the next row is separated by a comma. For example, the second row could be: two, four, six, eight, ten. Together, these rows form a single list or array. This makes it a two-dimensional array.

In [6]:
b = np.array([[1, 2, 3],     # 2-D array / Matrix
              [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(b)

numpy.ndarray

In [8]:
b.shape

(2, 3)

In [9]:
b.ndim

2

now 3 dimenstional array

In [10]:
# 3-D arrays

c = np.array([[[1.0, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])

d = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],

             [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

The first one (c) is a single 2D array wrapped inside another bracket, which makes it a 3D array with one plane.

The second one (d) contains two 2D arrays, enclosed together. Stacking 2D arrays in this way forms a 3D array.

In this case, there are two planes (or “layers”), so you can imagine it like a cube.

Although NumPy won’t visually show a cube, conceptually it represents 3D data.

In the same way, you can create 4D, 5D, or higher-dimensional arrays by nesting more layers.

In [13]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [12]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a.size, b.size, c.size, d.size # determine how many elements are there in an array

(3, 6, 9, 18)

In [14]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes # determine how many bytes consumed by an array

(24, 48, 72, 144)

## Array Creation

---

### Array Creation Functions in NumPy

1. **`np.zeros(shape)`**

   * Creates an array filled with **zeros**.
   * Example:

     ```python
     np.zeros((2, 3))
     # Output: [[0. 0. 0.]
     #          [0. 0. 0.]]
     ```

2. **`np.ones(shape)`**

   * Creates an array filled with **ones**.
   * Example:

     ```python
     np.ones((2, 3))
     # Output: [[1. 1. 1.]
     #          [1. 1. 1.]]
     ```

3. **`np.empty(shape)`**

   * Creates an array with **uninitialized values** (whatever happens to be in memory).
   * Faster than `zeros` or `ones`, but values will be random garbage.
   * Example:

     ```python
     np.empty((2, 3))
     ```

4. **`np.eye(N)`**

   * Creates an **identity matrix** (diagonal = 1, rest = 0).
   * Example:

     ```python
     np.eye(3)
     # Output:
     # [[1. 0. 0.]
     #  [0. 1. 0.]
     #  [0. 0. 1.]]
     ```

5. **`np.diag(v)`**

   * Creates a diagonal matrix from a list/array.
   * Example:

     ```python
     np.diag([1, 2, 3])
     # Output:
     # [[1 0 0]
     #  [0 2 0]
     #  [0 0 3]]
     ```

6. **`np.arange(start, end, step)`**

   * Creates a sequence of numbers from **start** to **end** (exclusive), with a given **step**.
   * Example:

     ```python
     np.arange(0, 10, 2)
     # Output: [0 2 4 6 8]
     ```

7. **`np.linspace(start, end, num)`**

   * Creates **evenly spaced numbers** between start and end (inclusive).
   * Example:

     ```python
     np.linspace(0, 1, 5)
     # Output: [0.   0.25 0.5  0.75 1. ]
     ```

---


see the link below for a wider explanation on how to use numpy for linear algebra, fourier analysis, and array manipulation in general.  

https://numpy.org/devdocs/user/quickstart.html

# Pandas

Is a library for tabular data manipulation. It is built upon Numpy and provides tools for data science. The basic data types in Pandas are the *Series* and the *DataFrame*

In [ ]:
import pandas as pd

Creating a Series by passing a list of values, letting pandas create a default integer index:

## Series

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s


In [ ]:
type(s)

or you can pass your own index:

In [ ]:
list('abcdef')

In [ ]:
index = list('abcdef')
values = [1, 3, 5, np.nan, 6, 8]
s = pd.Series(values, index = index)
s

Elements can be accessed with its index  

In [ ]:
print(s['a'])



## DataFrame

A *DataFrame* is an array of data in tabular form similar to that you can create in Excel:

Note, in other languages, such as R, DataFrames are built into the base language and it's not necessary to import a library.

In [ ]:
l1 = [10,20,30,40]
l2 = list('abcd')
l3 = [True, False, True, True]

d = {'A':l1, 'B':l2, 'C':l3}

df = pd.DataFrame(d)

df

In [ ]:
type(df)

Accesing the data. For columns you can pass the column name (or a list of them)

In [ ]:
df['A'] # return a Series

In [ ]:
df[['A','B']] # several columns must be passed as a list

If you want to filter certain rows, use the attribute `loc[]`:

In [ ]:
df

In [ ]:
df.loc[0]

In [ ]:
df

In [ ]:
df.loc[1,'C']

Boolean values can also be used:

In [ ]:
desired_rows = df['C']

df.loc[desired_rows]

Let' explore some important methods: `groupby` , `resample` and `rolling`



## groupby

In [ ]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})
df

In [ ]:
dir(df.groupby(['Animal']))

In [ ]:
df2 = df.groupby(['Animal']).last()
df2

Note that the original DataFrame doesn't change:

In [ ]:
df

## Resample

In [ ]:
index = pd.date_range('1/1/2000', periods=9, freq='T')
series = pd.Series(range(9), index=index)
series

In [ ]:
series.resample('3T').sum()

To learn more about the offset strings, please see:

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects

# rolling

In [ ]:
df = pd.DataFrame({'B': [0, 1, 2, 3, 4]})
df

In [ ]:
df.rolling(2).sum()

In [ ]:
df.rolling(3, center = True).sum()